[package]
name = "tfhe-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tfhe = { version = "0.1.11", features = [ "boolean", "shortint", "aarch64-unix" ] }
structopt = "0.3.21"